@startuml
package "TERRAFORM" {
    package "terraform" 
    package "adr"
    package "environments" {
        package "dev"
        package "prod"
        package "qa" {
            file "qa.auto.tfvars"
        }
    }
    package "modules" {
        package "data_sources"
        package "ec2" {
            file "ec2.tf"
            file "locals.tf"
            file "outputs.tf"
            file "variables.tf"
        }
        package "eip" {
            file "eip.tf"
            file "eip_association.tf"
            file "outputs.tf"
            file "variables.tf"
        }
        package "github" {
            file "github.tf"
            file "variables.tf"
        }
        package "iam" {
            file "iam.tf"
        }
        package "internet_gateway" {
            file "internet_gateway.tf"
        }
        package "public_subnets" {
            file "public_subnet.tf"
            file "outputs.tf"
            file "variables.tf"
        }
        package "random_ids" {
            file "random_id.tf"
        }
        package "route_tables" {
            file "route_table.tf"
            file "rt_association.tf"
        }
        package "routes" {
            file "route.tf"
        }
        package "s3" {
            file "locals.tf"
            file "outputs.tf"
        }
        package "security_groups" {
            file "s3_security.tf"
            file "vpc_security.tf"
        }
        package "vpc" {
            file "vpc.tf"
        }
    }
}
@enduml
